batch_size: 100000
hidden_dim: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  AgAAAAAAAAA=
hours: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  GAAAAAAAAAA=
in_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id002 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 73
  - *id001
  - false
  - !!binary |
    IgAAAAAAAABNAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAATAAAAAAAAAA0AAAAAAAAAGAAAAAAAAAAt
    AAAAAAAAACoAAAAAAAAADgAAAAAAAAAHAAAAAAAAAD4AAAAAAAAACwAAAAAAAABJAAAAAAAAACMA
    AAAAAAAABAAAAAAAAAAxAAAAAAAAAFEAAAAAAAAAKQAAAAAAAAA0AAAAAAAAAE8AAAAAAAAAOQAA
    AAAAAAAoAAAAAAAAAFMAAAAAAAAAPwAAAAAAAAAvAAAAAAAAAB8AAAAAAAAARAAAAAAAAAAzAAAA
    AAAAABQAAAAAAAAACgAAAAAAAABOAAAAAAAAABUAAAAAAAAAFgAAAAAAAAAZAAAAAAAAAAUAAAAA
    AAAAKwAAAAAAAAARAAAAAAAAABcAAAAAAAAAEAAAAAAAAAABAAAAAAAAADYAAAAAAAAAQgAAAAAA
    AABHAAAAAAAAAEMAAAAAAAAAQAAAAAAAAAASAAAAAAAAAEoAAAAAAAAASwAAAAAAAAA1AAAAAAAA
    ACAAAAAAAAAANwAAAAAAAABBAAAAAAAAADoAAAAAAAAAAwAAAAAAAAAnAAAAAAAAAEYAAAAAAAAA
    CQAAAAAAAAAGAAAAAAAAADAAAAAAAAAAUAAAAAAAAABFAAAAAAAAAC4AAAAAAAAAIQAAAAAAAABS
    AAAAAAAAAEwAAAAAAAAAHQAAAAAAAAAkAAAAAAAAADsAAAAAAAAALAAAAAAAAAAMAAAAAAAAADgA
    AAAAAAAASAAAAAAAAAA=
lr: !!python/object/apply:numpy.core.multiarray.scalar
- &id003 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  exSuR+F6hD8=
n_in_channels: 73
n_layers: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  AgAAAAAAAAA=
n_out_channels: 1
out_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id002
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 1
  - *id001
  - false
  - !!binary |
    AwAAAAAAAAA=
seq_len: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  CgAAAAAAAAA=
wd: !!python/object/apply:numpy.core.multiarray.scalar
- *id003
- !!binary |
  /Knx0k1iQD8=
