batch_size: 100000
hidden_dim: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  BQAAAAAAAAA=
hours: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  GAAAAAAAAAA=
in_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id002 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 72
  - *id001
  - false
  - !!binary |
    BwAAAAAAAABMAAAAAAAAAAIAAAAAAAAARgAAAAAAAAAXAAAAAAAAAFIAAAAAAAAASAAAAAAAAAAU
    AAAAAAAAACQAAAAAAAAAJQAAAAAAAAA6AAAAAAAAAA4AAAAAAAAAJgAAAAAAAAAnAAAAAAAAAEEA
    AAAAAAAAHQAAAAAAAAAGAAAAAAAAADIAAAAAAAAAEgAAAAAAAABTAAAAAAAAACAAAAAAAAAAPwAA
    AAAAAAABAAAAAAAAADAAAAAAAAAADQAAAAAAAAAfAAAAAAAAAB4AAAAAAAAASgAAAAAAAAAEAAAA
    AAAAAAsAAAAAAAAAQwAAAAAAAAAbAAAAAAAAAD4AAAAAAAAAIgAAAAAAAAAoAAAAAAAAADwAAAAA
    AAAATwAAAAAAAAAjAAAAAAAAABMAAAAAAAAAQgAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAFgAAAAAA
    AABJAAAAAAAAADEAAAAAAAAAUAAAAAAAAAARAAAAAAAAADQAAAAAAAAAUQAAAAAAAAAQAAAAAAAA
    AAgAAAAAAAAAOAAAAAAAAAAFAAAAAAAAADkAAAAAAAAALgAAAAAAAAApAAAAAAAAAA8AAAAAAAAA
    KwAAAAAAAAA9AAAAAAAAACwAAAAAAAAATQAAAAAAAABEAAAAAAAAAC0AAAAAAAAAGAAAAAAAAAAV
    AAAAAAAAADsAAAAAAAAAIQAAAAAAAAAzAAAAAAAAAEcAAAAAAAAANQAAAAAAAABLAAAAAAAAAAMA
    AAAAAAAA
lr: !!python/object/apply:numpy.core.multiarray.scalar
- &id003 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  /Knx0k1iQD8=
n_in_channels: 72
n_layers: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  AwAAAAAAAAA=
n_out_channels: 1
out_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id002
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 1
  - *id001
  - false
  - !!binary |
    AwAAAAAAAAA=
seq_len: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  eAAAAAAAAAA=
wd: !!python/object/apply:numpy.core.multiarray.scalar
- *id003
- !!binary |
  AAAAAAAA8D8=
