batch_size: 100000
hidden_dim: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  CgAAAAAAAAA=
hours: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  GAAAAAAAAAA=
in_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id002 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 75
  - *id001
  - false
  - !!binary |
    MwAAAAAAAABEAAAAAAAAAAEAAAAAAAAAPwAAAAAAAAAqAAAAAAAAACkAAAAAAAAAQwAAAAAAAAA+
    AAAAAAAAAB4AAAAAAAAALgAAAAAAAAAOAAAAAAAAADEAAAAAAAAAQgAAAAAAAABQAAAAAAAAABIA
    AAAAAAAAIQAAAAAAAABTAAAAAAAAABYAAAAAAAAAPQAAAAAAAABJAAAAAAAAADIAAAAAAAAAOAAA
    AAAAAAAYAAAAAAAAAE0AAAAAAAAADAAAAAAAAAA1AAAAAAAAAA0AAAAAAAAATgAAAAAAAAAJAAAA
    AAAAAAQAAAAAAAAAKwAAAAAAAAAsAAAAAAAAABoAAAAAAAAABQAAAAAAAAAnAAAAAAAAADsAAAAA
    AAAAEwAAAAAAAAAkAAAAAAAAAAAAAAAAAAAACwAAAAAAAAARAAAAAAAAADQAAAAAAAAABgAAAAAA
    AABPAAAAAAAAABkAAAAAAAAAGwAAAAAAAAA6AAAAAAAAAFEAAAAAAAAAFQAAAAAAAAAmAAAAAAAA
    ACgAAAAAAAAAQAAAAAAAAAAXAAAAAAAAADcAAAAAAAAACgAAAAAAAABGAAAAAAAAAEgAAAAAAAAA
    RwAAAAAAAAAIAAAAAAAAADkAAAAAAAAAHQAAAAAAAABMAAAAAAAAADAAAAAAAAAALQAAAAAAAABB
    AAAAAAAAACMAAAAAAAAAHAAAAAAAAABSAAAAAAAAAAMAAAAAAAAAEAAAAAAAAAACAAAAAAAAAB8A
    AAAAAAAAIAAAAAAAAABLAAAAAAAAAEUAAAAAAAAA
lr: !!python/object/apply:numpy.core.multiarray.scalar
- &id003 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  exSuR+F6dD8=
n_in_channels: 75
n_layers: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  CgAAAAAAAAA=
n_out_channels: 1
out_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id002
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 1
  - *id001
  - false
  - !!binary |
    AwAAAAAAAAA=
seq_len: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  CgAAAAAAAAA=
wd: !!python/object/apply:numpy.core.multiarray.scalar
- *id003
- !!binary |
  mpmZmZmZqT8=
