batch_size: 100000
hidden_dim: !!python/object/apply:numpy.core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  FAAAAAAAAAA=
hours: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  GAAAAAAAAAA=
in_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - &id002 !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 64
  - *id001
  - false
  - !!binary |
    SQAAAAAAAAAfAAAAAAAAADYAAAAAAAAAGgAAAAAAAAAkAAAAAAAAACwAAAAAAAAAIQAAAAAAAAAr
    AAAAAAAAADcAAAAAAAAAQQAAAAAAAAAmAAAAAAAAAD0AAAAAAAAAUQAAAAAAAAAcAAAAAAAAACUA
    AAAAAAAAEQAAAAAAAAA1AAAAAAAAADMAAAAAAAAAFwAAAAAAAAA+AAAAAAAAAFIAAAAAAAAAEgAA
    AAAAAAAxAAAAAAAAAE4AAAAAAAAABwAAAAAAAAAwAAAAAAAAADwAAAAAAAAAAQAAAAAAAAApAAAA
    AAAAACMAAAAAAAAAOQAAAAAAAAADAAAAAAAAACcAAAAAAAAAAgAAAAAAAAAgAAAAAAAAAAkAAAAA
    AAAASAAAAAAAAAA0AAAAAAAAABUAAAAAAAAALwAAAAAAAAAbAAAAAAAAAE0AAAAAAAAAQwAAAAAA
    AAAEAAAAAAAAAEwAAAAAAAAADAAAAAAAAABAAAAAAAAAAEUAAAAAAAAACAAAAAAAAAA6AAAAAAAA
    AB0AAAAAAAAAGAAAAAAAAAAGAAAAAAAAAEIAAAAAAAAAGQAAAAAAAAAiAAAAAAAAAC4AAAAAAAAA
    BQAAAAAAAAAtAAAAAAAAAAsAAAAAAAAACgAAAAAAAABEAAAAAAAAAEoAAAAAAAAAUwAAAAAAAAA=
lr: !!python/object/apply:numpy.core.multiarray.scalar
- &id003 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  LUMc6+I2Gj8=
n_in_channels: 64
n_layers: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  AwAAAAAAAAA=
n_out_channels: 1
out_channels: !!python/object/apply:numpy.core.multiarray._reconstruct
  args:
  - *id002
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 1
  - *id001
  - false
  - !!binary |
    AwAAAAAAAAA=
seq_len: !!python/object/apply:numpy.core.multiarray.scalar
- *id001
- !!binary |
  HgAAAAAAAAA=
wd: !!python/object/apply:numpy.core.multiarray.scalar
- *id003
- !!binary |
  mpmZmZmZqT8=
